version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gpiozero
    versions:
    - 1.5.1
    - 1.6.0
    - 1.6.1
  - dependency-name: pytz
    versions:
    - "2020.5"
