# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AbsPosition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, x: int=None, y: int=None, speed: int=10):  # noqa: E501
        """AbsPosition - a model defined in Swagger

        :param x: The x of this AbsPosition.  # noqa: E501
        :type x: int
        :param y: The y of this AbsPosition.  # noqa: E501
        :type y: int
        :param speed: The speed of this AbsPosition.  # noqa: E501
        :type speed: int
        """
        self.swagger_types = {
            'x': int,
            'y': int,
            'speed': int
        }

        self.attribute_map = {
            'x': 'x',
            'y': 'y',
            'speed': 'speed'
        }

        self._x = x
        self._y = y
        self._speed = speed

    @classmethod
    def from_dict(cls, dikt) -> 'AbsPosition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AbsPosition of this AbsPosition.  # noqa: E501
        :rtype: AbsPosition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x(self) -> int:
        """Gets the x of this AbsPosition.


        :return: The x of this AbsPosition.
        :rtype: int
        """
        return self._x

    @x.setter
    def x(self, x: int):
        """Sets the x of this AbsPosition.


        :param x: The x of this AbsPosition.
        :type x: int
        """
        if x is None:
            raise ValueError("Invalid value for `x`, must not be `None`")  # noqa: E501

        self._x = x

    @property
    def y(self) -> int:
        """Gets the y of this AbsPosition.


        :return: The y of this AbsPosition.
        :rtype: int
        """
        return self._y

    @y.setter
    def y(self, y: int):
        """Sets the y of this AbsPosition.


        :param y: The y of this AbsPosition.
        :type y: int
        """
        if y is None:
            raise ValueError("Invalid value for `y`, must not be `None`")  # noqa: E501

        self._y = y

    @property
    def speed(self) -> int:
        """Gets the speed of this AbsPosition.


        :return: The speed of this AbsPosition.
        :rtype: int
        """
        return self._speed

    @speed.setter
    def speed(self, speed: int):
        """Sets the speed of this AbsPosition.


        :param speed: The speed of this AbsPosition.
        :type speed: int
        """

        self._speed = speed
