#!/bin/sh
curl -H "Content-Type: application/json"\
  -X POST \
  -d '{"position": 350}' \
  http://192.168.21.7:5000/absolute/y
curl -H "Content-Type: application/json"\
  -X POST \
  -d '{"position": 425}' \
  http://192.168.21.7:5000/absolute/x
